//
// LuisPa 2017/01/06
//
// Este fichero solo se utiliza para la generación del M3U, no para EPG. 
//
// Disclaimer: 
//
// Aquí tenemos la lista de canales en SD que voy a añadir el fichero m3u con las 
// etiquetas "SD|REMOTE". Como podrás observar aquí he puesto las versiones
// en SD, con la fuente Movistar adecuada, de los canales que tengo en el 
// fichero cadenasHOME.js de modo que cuando un cliente Tvheadend seleccione
// (o se asocie) al TAG REMOTE solo recibirá estos canales. 
//
// El caso de uso es el de poder separar qué tipo de canales quiero recibir
// en dispositivo tablet vía Wifi. 
//
// Esta forma de trabajar es muy personal, si prefieres utilizar otra técnica
// juega con ambos ficheros y las etiquetas 'tvh_tag' para adaptarlo a tu gusto. 
//
// Cadenas de TV exclusivamente en 'SD', que etiqueto con 'REMOTE' para 
// poder hacer filtros en Tvheadend. Principalmente orientado a Tablets
//
const cadenasREMOTE = [
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.76:8208",
    "movistar_id": "TVE",
    "movistar_nombre": "LA 1",
    "movistar_numero": "1",
    "tvh_id": "TVE.es",
    "tvh_m3u": true,
    "tvh_nombre": "La 1",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.2:8208",
    "movistar_id": "LA2",
    "movistar_nombre": "LA 2",
    "movistar_numero": "2",
    "tvh_id": "LA2.es",
    "tvh_m3u": true,
    "tvh_nombre": "La 2",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.3:8208",
    "movistar_id": "A3",
    "movistar_nombre": "Antena 3",
    "movistar_numero": "3",
    "tvh_id": "A3.es",
    "tvh_m3u": true,
    "tvh_nombre": "Antena 3",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.4:8208",
    "movistar_id": "C4",
    "movistar_nombre": "Cuatro",
    "movistar_numero": "4",
    "tvh_id": "C4.es",
    "tvh_m3u": true,
    "tvh_nombre": "Cuatro",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.5:8208",
    "movistar_id": "T5",
    "movistar_nombre": "Telecinco",
    "movistar_numero": "5",
    "tvh_id": "T5.es",
    "tvh_m3u": true,
    "tvh_nombre": "Telecinco",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.58:8208",
    "movistar_id": "SEXTA",
    "movistar_nombre": "La Sexta",
    "movistar_numero": "6",
    "tvh_id": "SEXTA.es",
    "tvh_m3u": true,
    "tvh_nombre": "La Sexta",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.108:8208",
    "movistar_id": "MV3",
    "movistar_nombre": "#0",
    "movistar_numero": "7",
    "tvh_id": "MV3.es",
    "tvh_m3u": true,
    "tvh_nombre": "#0",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.25:8208",
    "movistar_id": "DESCONOCIDO2",
    "movistar_nombre": "Telemadrid",
    "movistar_numero": "8",
    "tvh_id": "Telemadrid.es",
    "tvh_m3u": true,
    "tvh_nombre": "Telemadrid",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.26:8208",
    "movistar_id": "OTRA",
    "movistar_nombre": "La Otra",
    "movistar_numero": "9",
    "tvh_id": "OTRA.es",
    "tvh_m3u": true,
    "tvh_nombre": "La Otra",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.3.32:8208", 
    "movistar_id": "CABECERA_SERIES",
    "movistar_nombre": "SERIES",
    "movistar_numero": "10",
    "tvh_id": "CABECERA_SERIES.es",
    "tvh_m3u": true,
    "tvh_nombre": "CABECERA SERIES",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.5.4:8208",
    "movistar_id": "CPSER",
    "movistar_nombre": "Movistar Series",
    "movistar_numero": "11",
    "tvh_id": "CPSER.es",
    "tvh_m3u": true,
    "tvh_nombre": "Movistar Series",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.3.20:8208",
    "movistar_id": "MV2",
    "movistar_nombre": "Movistar Series Xtra",
    "movistar_numero": "12",
    "tvh_id": "MV2.es",
    "tvh_m3u": true,
    "tvh_nombre": "Movistar Series Xtra",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.74:8208",
    "movistar_id": "FOXGE",
    "movistar_nombre": "Fox",
    "movistar_numero": "13",
    "tvh_id": "FOXGE.es",
    "tvh_m3u": true,
    "tvh_nombre": "FOX",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.14:8208",
    "movistar_id": "AXN",
    "movistar_nombre": "AXN",
    "movistar_numero": "14",
    "tvh_id": "AXN.es",
    "tvh_m3u": true,
    "tvh_nombre": "AXN",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.44:8208",
    "movistar_id": "TNT",
    "movistar_nombre": "TNT",
    "movistar_numero": "15",
    "tvh_id": "TNT.es",
    "tvh_m3u": true,
    "tvh_nombre": "TNT",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.68:8208",
    "movistar_id": "PCM",
    "movistar_nombre": "Comedy Central",
    "movistar_numero": "16",
    "tvh_id": "PCM.es",
    "tvh_m3u": true,
    "tvh_nombre": "Comedy Central",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.13:8208",
    "movistar_id": "CL13",
    "movistar_nombre": "Calle 13",
    "movistar_numero": "17",
    "tvh_id": "CL13.es",
    "tvh_m3u": true,
    "tvh_nombre": "Calle 13",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.15:8208",
    "movistar_id": "COSMO",
    "movistar_nombre": "COSMO",
    "movistar_numero": "18",
    "tvh_id": "COSMO.es",
    "tvh_m3u": true,
    "tvh_nombre": "COSMO",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.8:8208",
    "movistar_id": "AMC",
    "movistar_nombre": "AMC",
    "movistar_numero": "19",
    "tvh_id": "AMC.es",
    "tvh_m3u": true,
    "tvh_nombre": "AMC",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.112:8208",
    "movistar_id": "FOXCR",
    "movistar_nombre": "Fox Life",
    "movistar_numero": "20",
    "tvh_id": "FOXCR.es",
    "tvh_m3u": true,
    "tvh_nombre": "FOX life",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.62:8208",
    "movistar_id": "SET",
    "movistar_nombre": "AXN White",
    "movistar_numero": "21",
    "tvh_id": "SET.es",
    "tvh_m3u": true,
    "tvh_nombre": "AXN White",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.111:8208",
    "movistar_id": "SCI-FI",
    "movistar_nombre": "SYFY",
    "movistar_numero": "22",
    "tvh_id": "SCI-FI.es",
    "tvh_m3u": true,
    "tvh_nombre": "SyFy",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.212:8208",
    "movistar_id": "NONSTP",
    "movistar_nombre": "Non Stop People",
    "movistar_numero": "23",
    "tvh_id": "NONSTP.es",
    "tvh_m3u": true,
    "tvh_nombre": "Non Stop People",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.211:8208",
    "movistar_id": "MTV",
    "movistar_nombre": "MTV",
    "movistar_numero": "24",
    "tvh_id": "MTV.es",
    "tvh_m3u": true,
    "tvh_nombre": "MTV",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.84:8208",
    "movistar_id": "FDFIC",
    "movistar_nombre": "Factoría de Ficción",
    "movistar_numero": "25",
    "tvh_id": "FDFIC.es",
    "tvh_m3u": true,
    "tvh_nombre": "Factoría de Ficción",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.107:8208",
    "movistar_id": "NEOX",
    "movistar_nombre": "Neox",
    "movistar_numero": "26",
    "tvh_id": "NEOX.es",
    "tvh_m3u": true,
    "tvh_nombre": "Neox",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.3.29:8208",
    "movistar_id": "ATRESS",
    "movistar_nombre": "Atreseries",
    "movistar_numero": "27",
    "tvh_id": "ATRESS.es",
    "tvh_m3u": true,
    "tvh_nombre": "Atreseries HD",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.59:8208",
    "movistar_id": "ENERGY",
    "movistar_nombre": "Energy",
    "movistar_numero": "28",
    "tvh_id": "ENERGY.es",
    "tvh_m3u": true,
    "tvh_nombre": "Energy",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.3.30:8208",
    "movistar_id": "CABECERA_CINE",
    "movistar_nombre": "CINE",
    "movistar_numero": "30",
    "tvh_id": "CABECERA_CINE.es",
    "tvh_m3u": true,
    "tvh_nombre": "CABECERA CINE",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.3.40:8208",
    "movistar_id": "MV1",
    "movistar_nombre": "Movistar Estrenos",
    "movistar_numero": "31",
    "tvh_id": "MV1.es",
    "tvh_m3u": true,
    "tvh_nombre": "Movistar Estrenos",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.3.41:8208",
    "movistar_id": "CPXTRA",
    "movistar_nombre": "Movistar Xtra",
    "movistar_numero": "32",
    "tvh_id": "CPXTRA.es",
    "tvh_m3u": true,
    "tvh_nombre": "Movistar Xtra",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.3.42:8208",
    "movistar_id": "CPACCI",
    "movistar_nombre": "Movistar Acción",
    "movistar_numero": "33",
    "tvh_id": "CPACCI.es",
    "tvh_m3u": true,
    "tvh_nombre": "Movistar Acción",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.3.43:8208",
    "movistar_id": "CPCOME",
    "movistar_nombre": "Movistar Comedia",
    "movistar_numero": "34",
    "tvh_id": "CPCOME.es",
    "tvh_m3u": true,
    "tvh_nombre": "Movistar Comedia",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.3.44:8208",
    "movistar_id": "CPCOLE",
    "movistar_nombre": "Movistar DCine",
    "movistar_numero": "35",
    "tvh_id": "CPCOLE.es",
    "tvh_m3u": true,
    "tvh_nombre": "Movistar DCine",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.3.45:8208",
    "movistar_id": "DCESP",
    "movistar_nombre": "Movistar Cine Español",
    "movistar_numero": "36",
    "tvh_id": "DCESP.es",
    "tvh_m3u": true,
    "tvh_nombre": "Movistar Cine Español",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.6.5:8208",
    "movistar_id": "TCM",
    "movistar_nombre": "TCM",
    "movistar_numero": "37",
    "tvh_id": "TCM.es",
    "tvh_m3u": true,
    "tvh_nombre": "TCM",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.16:8208",
    "movistar_id": "HOLLYW",
    "movistar_nombre": "Hollywood",
    "movistar_numero": "38",
    "tvh_id": "HOLLYW.es",
    "tvh_m3u": true,
    "tvh_nombre": "Hollywood",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.102:8208",
    "movistar_id": "SUNDAN",
    "movistar_nombre": "Sundance",
    "movistar_numero": "39",
    "tvh_id": "SUNDAN.es",
    "tvh_m3u": true,
    "tvh_nombre": "Sundance Channel",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.39:8208",
    "movistar_id": "DARK",
    "movistar_nombre": "DARK",
    "movistar_numero": "40",
    "tvh_id": "DARK.es",
    "tvh_m3u": true,
    "tvh_nombre": "DARK",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.91:8208",
    "movistar_id": "13TV",
    "movistar_nombre": "13 TV",
    "movistar_numero": "41",
    "tvh_id": "13TV.es",
    "tvh_m3u": true,
    "tvh_nombre": "13 TV",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.34:8208",
    "movistar_id": "TEN",
    "movistar_nombre": "TEN",
    "movistar_numero": "42",
    "tvh_id": "TEN.es",
    "tvh_m3u": true,
    "tvh_nombre": "TEN",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.90:8208",
    "movistar_id": "PARCH",
    "movistar_nombre": "Paramount Channel",
    "movistar_numero": "43",
    "tvh_id": "PARCH.es",
    "tvh_m3u": true,
    "tvh_nombre": "Paramount Channel",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.3.33:8208",
    "movistar_id": "CABECERA DEPORTES",
    "movistar_nombre": "DEPORTES",
    "movistar_numero": "44",
    "tvh_categoria": "Sports",
    "tvh_id": "CABECERA_DEPORTES.es",
    "tvh_m3u": true,
    "tvh_nombre": "CABECERA DEPORTES",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.6.8:8208",
    "movistar_id": "CPFUT",
    "movistar_nombre": "Movistar Fútbol",
    "movistar_numero": "45",
    "tvh_categoria": "Sports",
    "tvh_id": "CPFUT.es",
    "tvh_m3u": true,
    "tvh_nombre": "Movistar Fútbol",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.4.129:8208",
    "movistar_id": "CPPART",
    "movistar_nombre": "Movistar Partidazo",
    "movistar_numero": "46",
    "tvh_categoria": "Sports",
    "tvh_id": "CPPART.es",
    "tvh_m3u": true,
    "tvh_nombre": "Movistar Partidazo",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.46:8208",
    "movistar_id": "BELIGA",
    "movistar_nombre": "Bein LaLiga",
    "movistar_numero": "47",
    "tvh_categoria": "Sports",
    "tvh_id": "BELIGA.es",
    "tvh_m3u": true,
    "tvh_nombre": "Bein LaLiga",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.47:8208",
    "movistar_id": "BELIG1",
    "movistar_nombre": "Bein LaLiga 1",
    "movistar_numero": "48",
    "tvh_categoria": "Sports",
    "tvh_id": "BELIG1.es",
    "tvh_m3u": true,
    "tvh_nombre": "Bein LaLiga 1",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.67:8208",
    "movistar_id": "BELIG2",
    "movistar_nombre": "Bein LaLiga 2",
    "movistar_numero": "49",
    "tvh_categoria": "Sports",
    "tvh_id": "BELIG2.es",
    "tvh_m3u": true,
    "tvh_nombre": "Bein LaLiga 2",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.3.100:8208",
    "movistar_id": "CHUEFA",
    "movistar_nombre": "beIN SPORTS ",
    "movistar_numero": "50",
    "tvh_categoria": "Sports",
    "tvh_id": "CHUEFA.es",
    "tvh_m3u": true,
    "tvh_nombre": "beIN SPORTS",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.3.101:8208",
    "movistar_id": "BEMAX1",
    "movistar_nombre": "Bein Max1",
    "movistar_numero": "51",
    "tvh_categoria": "Sports",
    "tvh_id": "BEMAX1.es",
    "tvh_m3u": true,
    "tvh_nombre": "Bein Max1",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.3.102:8208",
    "movistar_id": "BEMAX2",
    "movistar_nombre": "Bein Max2",
    "movistar_numero": "52",
    "tvh_categoria": "Sports",
    "tvh_id": "BEMAX2.es",
    "tvh_m3u": true,
    "tvh_nombre": "Bein Max2",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.83:8208",
    "movistar_id": "REALM",
    "movistar_nombre": "Real Madrid TV",
    "movistar_numero": "53",
    "tvh_categoria": "Sports",
    "tvh_id": "REALM.es",
    "tvh_m3u": true,
    "tvh_nombre": "Real Madrid TV",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.3.65:8208",
    "movistar_id": "BARNA",
    "movistar_nombre": "Barça TV",
    "movistar_numero": "54",
    "tvh_categoria": "Sports",
    "tvh_id": "BARNA.es",
    "tvh_m3u": false,
    "tvh_nombre": "Barça TV",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.4.193:8208",
    "movistar_id": "CPDEP",
    "movistar_nombre": "Movistar Deportes 1",
    "movistar_numero": "55",
    "tvh_categoria": "Sports",
    "tvh_id": "CPDEP.es",
    "tvh_m3u": true,
    "tvh_nombre": "Movistar Deportes 1",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.5.5:8208",
    "movistar_id": "CPD2",
    "movistar_nombre": "Movistar Deportes 2",
    "movistar_numero": "56",
    "tvh_categoria": "Sports",
    "tvh_id": "CPD2.es",
    "tvh_m3u": true,
    "tvh_nombre": "Movistar Deportes 2",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.1.246:8208",
    "movistar_id": "MVF1",
    "movistar_nombre": "Movistar Fórmula 1",
    "movistar_numero": "57",
    "tvh_categoria": "Sports",
    "tvh_id": "MVF1.es",
    "tvh_m3u": true,
    "tvh_nombre": "Movistar Fórmula 1",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.3.38:8208",
    "movistar_id": "MVMTGP",
    "movistar_nombre": "Movistar Moto GP",
    "movistar_numero": "58",
    "tvh_categoria": "Sports",
    "tvh_id": "MVMTGP.es",
    "tvh_m3u": true,
    "tvh_nombre": "Movistar Moto GP",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.5.2:8208",
    "movistar_id": "GOLF+",
    "movistar_nombre": "Movistar Golf",
    "movistar_numero": "59",
    "tvh_categoria": "Sports",
    "tvh_id": "GOLF.TV.es",
    "tvh_m3u": true,
    "tvh_nombre": "Movistar Golf",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.18:8208",
    "movistar_id": "ESP",
    "movistar_nombre": "Eurosport 1",
    "movistar_numero": "60",
    "tvh_categoria": "Sports",
    "tvh_id": "ESP.es",
    "tvh_m3u": true,
    "tvh_nombre": "Eurosport 1",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.37:8208",
    "movistar_id": "ESP2",
    "movistar_nombre": "Eurosport 2",
    "movistar_numero": "61",
    "tvh_categoria": "Sports",
    "tvh_id": "ESP2.es",
    "tvh_m3u": true,
    "tvh_nombre": "Eurosport 2",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.7:8208",
    "movistar_id": "GOLHD",
    "movistar_nombre": "GOL",
    "movistar_numero": "62",
    "tvh_categoria": "Sports",
    "tvh_id": "GOLHD.es",
    "tvh_m3u": true,
    "tvh_nombre": "GOL",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.79:8208",
    "movistar_id": "TDEP",
    "movistar_nombre": "Teledeporte",
    "movistar_numero": "63",
    "tvh_categoria": "Sports",
    "tvh_id": "TDEP.es",
    "tvh_m3u": true,
    "tvh_nombre": "Teledeporte",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.97:8208",
    "movistar_id": "FUTREP",
    "movistar_nombre": "Canal Fútbol Replay",
    "movistar_numero": "64",
    "tvh_categoria": "Sports",
    "tvh_id": "FUTREP.es",
    "tvh_m3u": true,
    "tvh_nombre": "Canal Fútbol Replay",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.6.54:8208",
    "movistar_id": "CAZPES",
    "movistar_nombre": "Caza y Pesca",
    "movistar_numero": "65",
    "tvh_categoria": "Nature / Animals / Environment",
    "tvh_id": "CAZPES.es",
    "tvh_m3u": true,
    "tvh_nombre": "Caza y Pesca",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.5.188:8208",
    "movistar_id": "IBERAL",
    "movistar_nombre": "Iberalia TV",
    "movistar_numero": "66",
    "tvh_id": "IBERAL.es",
    "tvh_m3u": false,
    "tvh_nombre": "Iberalia TV",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.1.140:8208",
    "movistar_id": "CFERIA",
    "movistar_nombre": "Toros TV",
    "movistar_numero": "67",
    "tvh_categoria": "Arts / Culture (without music)",
    "tvh_id": "CFERIA.es",
    "tvh_m3u": true,
    "tvh_nombre": "Toros TV",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.103:8208",
    "movistar_id": "NATGEO",
    "movistar_nombre": "National Geographic",
    "movistar_numero": "70",
    "tvh_categoria": "Education / Science / Factual topics",
    "tvh_id": "NATGEO.es",
    "tvh_m3u": true,
    "tvh_nombre": "National Geographic",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.89:8208",
    "movistar_id": "NATGW",
    "movistar_nombre": "Nat Geo Wild",
    "movistar_numero": "71",
    "tvh_categoria": "Education / Science / Factual topics",
    "tvh_id": "NATGW.es",
    "tvh_m3u": true,
    "tvh_nombre": "Nat Geo Wild",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.19:8208",
    "movistar_id": "HIST",
    "movistar_nombre": "Historia",
    "movistar_numero": "72",
    "tvh_categoria": "Education / Science / Factual topics",
    "tvh_id": "HIST.es",
    "tvh_m3u": true,
    "tvh_nombre": "Historia",
    "tvh_tag": "SD|REMOTE"
  }, 
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.21:8208",
    "movistar_id": "DCR",
    "movistar_nombre": "Discovery",
    "movistar_numero": "73",
    "tvh_categoria": "Education / Science / Factual topics",
    "tvh_id": "DCR.es",
    "tvh_m3u": true,
    "tvh_nombre": "Discovery Channel",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.22:8208",
    "movistar_id": "ODISEA",
    "movistar_nombre": "Odisea",
    "movistar_numero": "74",
    "tvh_id": "ODISEA.es",
    "tvh_m3u": true,
    "tvh_nombre": "Odisea",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.38:8208",
    "movistar_id": "BIOGRA",
    "movistar_nombre": "A&E",
    "movistar_numero": "75",
    "tvh_id": "BIOGRA.es",
    "tvh_m3u": true,
    "tvh_nombre": "A&E",
    "tvh_tag": "SD|REMOTE"
  },  
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.20:8208",
    "movistar_id": "VJR",
    "movistar_nombre": "Viajar",
    "movistar_numero": "76",
    "tvh_categoria": "Arts / Culture (without music)",
    "tvh_id": "VJR.es",
    "tvh_m3u": true,
    "tvh_nombre": "Viajar",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.32:8208",
    "movistar_id": "DCRMAX",
    "movistar_nombre": "Discovery Max",
    "movistar_numero": "77",
    "tvh_categoria": "Education / Science / Factual topics",
    "tvh_id": "DCRMAX.es",
    "tvh_m3u": true,
    "tvh_nombre": "Discovery Max",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.57:8208",
    "movistar_id": "CYM",
    "movistar_nombre": "Crimen + Investigación",
    "movistar_numero": "78",
    "tvh_id": "CYM.es",
    "tvh_m3u": true,
    "tvh_nombre": "Crimen & Investigación",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.65:8208",
    "movistar_id": "CCTV-E",
    "movistar_nombre": "CCTV Español",
    "movistar_numero": "79",
    "tvh_id": "CCTV-E.es",
    "tvh_m3u": true,
    "tvh_nombre": "CCTV Español",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.27:8208",
    "movistar_id": "CACOC",
    "movistar_nombre": "Canal Cocina",
    "movistar_numero": "80",
    "tvh_categoria": "Arts / Culture (without music)",
    "tvh_id": "CACOC.es",
    "tvh_m3u": true,
    "tvh_nombre": "Canal Cocina",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.71:8208",
    "movistar_id": "DECASA",
    "movistar_nombre": "Canal Decasa",
    "movistar_numero": "81",
    "tvh_id": "DECASA.es",
    "tvh_m3u": true,
    "tvh_nombre": "Canal Decasa",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.6:8208",
    "movistar_id": "DKISS",
    "movistar_nombre": "DKISS",
    "movistar_numero": "82",
    "tvh_id": "DKISS.es",
    "tvh_m3u": true,
    "tvh_nombre": "DKISS",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.48:8208",
    "movistar_id": "DIVINI",
    "movistar_nombre": "Divinity",
    "movistar_numero": "83",
    "tvh_id": "DIVINI.es",
    "tvh_m3u": true,
    "tvh_nombre": "Divinity",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.106:8208",
    "movistar_id": "NOVA",
    "movistar_nombre": "Nova",
    "movistar_numero": "84",
    "tvh_id": "NOVA.es",
    "tvh_m3u": true,
    "tvh_nombre": "Nova",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.3.31:8208",
    "movistar_id": "MEGA",
    "movistar_nombre": "Mega",
    "movistar_numero": "85",
    "tvh_id": "MEGA.es",
    "tvh_m3u": true,
    "tvh_nombre": "Mega",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.17:8208",
    "movistar_id": "BEMAD",
    "movistar_nombre": "BE MAD",
    "movistar_numero": "86",
    "tvh_id": "BEMAD.es",
    "tvh_m3u": true,
    "tvh_nombre": "BEMAD",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.99:8208",
    "movistar_id": "GARAGE",
    "movistar_nombre": "Garage TV",
    "movistar_numero": "87",
    "tvh_id": "GARAGE.es",
    "tvh_m3u": true,
    "tvh_nombre": "Garage TV",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.45:8208",
    "movistar_id": "ORBE21",
    "movistar_nombre": "Canal Orbe 21",
    "movistar_numero": "88",
    "tvh_id": "ORBE21.es",
    "tvh_m3u": true,
    "tvh_nombre": "Canal Orbe 21",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.113:8208",
    "movistar_id": "BABY",
    "movistar_nombre": "Baby TV",
    "movistar_numero": "90",
    "tvh_categoria": "Children's / Youth programs",
    "tvh_id": "BABY.es",
    "tvh_m3u": true,
    "tvh_nombre": "Baby TV",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.10:8208",
    "movistar_id": "PLAYDC",
    "movistar_nombre": "Disney Junior",
    "movistar_numero": "91",
    "tvh_categoria": "Children's / Youth programs",
    "tvh_id": "PLAYDC.es",
    "tvh_m3u": true,
    "tvh_nombre": "Disney Junior",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.117:8208",
    "movistar_id": "PANDA",
    "movistar_nombre": "Canal Panda",
    "movistar_numero": "92",
    "tvh_categoria": "Children's / Youth programs",
    "tvh_id": "PANDA.es",
    "tvh_m3u": true,
    "tvh_nombre": "Canal Panda",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.115:8208",
    "movistar_id": "NICKJR",
    "movistar_nombre": "NICK JR",
    "movistar_numero": "93",
    "tvh_categoria": "Children's / Youth programs",
    "tvh_id": "NICKJR.es",
    "tvh_m3u": true,
    "tvh_nombre": "Nick Jr",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.69:8208",
    "movistar_id": "NICK",
    "movistar_nombre": "Nickelodeon",
    "movistar_numero": "94",
    "tvh_categoria": "Children's / Youth programs",
    "tvh_id": "NICK.es",
    "tvh_m3u": true,
    "tvh_nombre": "Nickelodeon",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.11:8208",
    "movistar_id": "DCHXD",
    "movistar_nombre": "Disney XD",
    "movistar_numero": "95",
    "tvh_categoria": "Children's / Youth programs",
    "tvh_id": "DCHXD.es",
    "tvh_m3u": true,
    "tvh_nombre": "Disney XD",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.64:8208",
    "movistar_id": "DCH",
    "movistar_nombre": "Disney Channel",
    "movistar_numero": "96",
    "tvh_categoria": "Children's / Youth programs",
    "tvh_id": "DCH.es",
    "tvh_m3u": true,
    "tvh_nombre": "Disney Channel",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.66:8208",
    "movistar_id": "BOING",
    "movistar_nombre": "Boing",
    "movistar_numero": "97",
    "tvh_categoria": "Children's / Youth programs",
    "tvh_id": "BOING.es",
    "tvh_m3u": true,
    "tvh_nombre": "Boing",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.80:8208",
    "movistar_id": "CLANTV",
    "movistar_nombre": "Clan TVE",
    "movistar_numero": "98",
    "tvh_categoria": "Children's / Youth programs",
    "tvh_id": "CLANTV.es",
    "tvh_m3u": true,
    "tvh_nombre": "Clan TVE",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.12:8208",
    "movistar_id": "40TV",
    "movistar_nombre": "Los40",
    "movistar_numero": "103",
    "tvh_categoria": "Music / Ballet / Dance",
    "tvh_id": "Los40.es",
    "tvh_m3u": true,
    "tvh_nombre": "Los40",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.75:8208",
    "movistar_id": "VH1",
    "movistar_nombre": "VH1",
    "movistar_numero": "105",
    "tvh_categoria": "Music / Ballet / Dance",
    "tvh_id": "VH1.es",
    "tvh_m3u": true,
    "tvh_nombre": "VH1",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": true,
    "movistar_fuente": "239.0.4.65:8208",
    "movistar_id": "MEZZO",
    "movistar_nombre": "Mezzo",
    "movistar_numero": "107",
    "tvh_categoria": "Music / Ballet / Dance",
    "tvh_id": "MEZZO.es",
    "tvh_m3u": true,
    "tvh_nombre": "Mezzo HD",
    "tvh_tag": "HD|HOME"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.3.193:8208",
    "movistar_id": "CLASSI",
    "movistar_nombre": "Classica HD",
    "movistar_numero": "109",
    "tvh_categoria": "Music / Ballet / Dance",
    "tvh_id": "CLASSI.es",
    "tvh_m3u": true,
    "tvh_nombre": "Classica",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.30:8208",
    "movistar_id": "BBC",
    "movistar_nombre": "BBC World",
    "movistar_numero": "113",
    "tvh_categoria": "News / Current affairs",
    "tvh_id": "BBC.es",
    "tvh_m3u": true,
    "tvh_nombre": "BBC World News",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.40:8208",
    "movistar_id": "CNN",
    "movistar_nombre": "CNN Int",
    "movistar_numero": "114",
    "tvh_categoria": "News / Current affairs",
    "tvh_id": "CNN.es",
    "tvh_m3u": true,
    "tvh_nombre": "CNN International",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.7.65:8208",
    "movistar_id": "FOXNWS",
    "movistar_nombre": "Fox News",
    "movistar_numero": "115",
    "tvh_categoria": "News / Current affairs",
    "tvh_id": "FOXNWS.es",
    "tvh_m3u": true,
    "tvh_nombre": "FOX News",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.28:8208",
    "movistar_id": "ENW",
    "movistar_nombre": "Euronews",
    "movistar_numero": "116",
    "tvh_categoria": "News / Current affairs",
    "tvh_id": "ENW.es",
    "tvh_m3u": true,
    "tvh_nombre": "Euronews",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.7.66:8208",
    "movistar_id": "ALJAZE",
    "movistar_nombre": "Al Jazeera",
    "movistar_numero": "117",
    "tvh_categoria": "News / Current affairs",
    "tvh_id": "ALJAZE.es",
    "tvh_m3u": false,
    "tvh_nombre": "Al Jazeera",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.7.67:8208",
    "movistar_id": "FRA EN",
    "movistar_nombre": "FRANCE 24",
    "movistar_numero": "118",
    "tvh_categoria": "News / Current affairs",
    "tvh_id": "FRA.EN.es",
    "tvh_m3u": true,
    "tvh_nombre": "France 24",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.7.67:8208",
    "movistar_id": "RTESP",
    "movistar_nombre": "RT Español",
    "movistar_numero": "119",
    "tvh_categoria": "News / Current affairs",
    "tvh_id": "RTESP.es",
    "tvh_m3u": true,
    "tvh_nombre": "RT Español",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.7.69:8208",
    "movistar_id": "NBC",
    "movistar_nombre": "CNBC",
    "movistar_numero": "120",
    "tvh_categoria": "News / Current affairs",
    "tvh_id": "NBC.es",
    "tvh_m3u": true,
    "tvh_nombre": "CNBC Europe",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.31:8208",
    "movistar_id": "TV5",
    "movistar_nombre": "TV5MONDE",
    "movistar_numero": "122",
    "tvh_categoria": "News / Current affairs",
    "tvh_id": "TV5.es",
    "tvh_m3u": true,
    "tvh_nombre": "TV5MONDE",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.29:8208",
    "movistar_id": "BL",
    "movistar_nombre": "Bloomberg",
    "movistar_numero": "123",
    "tvh_categoria": "News / Current affairs",
    "tvh_id": "BL.es",
    "tvh_m3u": true,
    "tvh_nombre": "Bloomberg",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.63:8208",
    "movistar_id": "INTECO",
    "movistar_nombre": "Intereconomía TV",
    "movistar_numero": "124",
    "tvh_categoria": "News / Current affairs",
    "tvh_id": "INTECO.es",
    "tvh_m3u": true,
    "tvh_nombre": "Intereconomía TV",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.85:8208",
    "movistar_id": "LIBDIG",
    "movistar_nombre": "Libertad Digital",
    "movistar_numero": "125",
    "tvh_categoria": "News / Current affairs",
    "tvh_id": "LIBDIG.es",
    "tvh_m3u": true,
    "tvh_nombre": "Libertad Digital",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.220:8208",
    "movistar_id": "312",
    "movistar_nombre": "i24news",
    "movistar_numero": "128",
    "tvh_categoria": "News / Current affairs",
    "tvh_id": "312.es",
    "tvh_m3u": true,
    "tvh_nombre": "i24news",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.221:8208",
    "movistar_id": "CNCWOR",
    "movistar_nombre": "CNC World",
    "movistar_numero": "129",
    "tvh_id": "CNCWOR.es",
    "tvh_m3u": true,
    "tvh_nombre": "CNC World",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.8.3:8208",
    "movistar_id": "TELEFE",
    "movistar_nombre": "Telefe Internacional",
    "movistar_numero": "134",
    "tvh_id": "TELEFE.es",
    "tvh_m3u": false,
    "tvh_nombre": "Telefe Internacional",
    "tvh_tag": "SD|TV"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.8.193:8208",
    "movistar_id": "GALAV",
    "movistar_nombre": "Canal de las Estrellas",
    "movistar_numero": "135",
    "tvh_id": "GALAV.es",
    "tvh_m3u": false,
    "tvh_nombre": "Canal de las Estrellas",
    "tvh_tag": "SD|TV"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.7.129:8208",
    "movistar_id": "CARACO",
    "movistar_nombre": "Caracol TV",
    "movistar_numero": "136",
    "tvh_id": "CARACO.es",
    "tvh_m3u": false,
    "tvh_nombre": "Caracol TV",
    "tvh_tag": "SD|TV"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.8.2:8208",
    "movistar_id": "TVREC",
    "movistar_nombre": "TV RECORD",
    "movistar_numero": "137",
    "tvh_id": "TVREC.es",
    "tvh_m3u": false,
    "tvh_nombre": "TV Record",
    "tvh_tag": "SD|TV"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.8.1:8208",
    "movistar_id": "CHILE",
    "movistar_nombre": "TV Chile",
    "movistar_numero": "138",
    "tvh_id": "CHILE.es",
    "tvh_m3u": false,
    "tvh_nombre": "TV Chile",
    "tvh_tag": "SD|TV"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.7.131:8208",
    "movistar_id": "COLOMB",
    "movistar_nombre": "TV Colombia",
    "movistar_numero": "139",
    "tvh_id": "COLOMB.es",
    "tvh_m3u": false,
    "tvh_nombre": "TV Colombia",
    "tvh_tag": "SD|TV"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.8.68:8208",
    "movistar_id": "AZMUND",
    "movistar_nombre": "AZ Mundo",
    "movistar_numero": "140",
    "tvh_id": "AZMUND.es",
    "tvh_m3u": false,
    "tvh_nombre": "AZ Mundo",
    "tvh_tag": "SD|TV"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.8.67:8208",
    "movistar_id": "CUBAV",
    "movistar_nombre": "Cubavisión",
    "movistar_numero": "141",
    "tvh_id": "CUBAV.es",
    "tvh_m3u": false,
    "tvh_nombre": "Cubavisión",
    "tvh_tag": "SD|TV"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.8.69:8208",
    "movistar_id": "TLESUR",
    "movistar_nombre": "Telesur",
    "movistar_numero": "142",
    "tvh_id": "TLESUR.es",
    "tvh_m3u": false,
    "tvh_nombre": "Telesur",
    "tvh_tag": "SD|TV"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.1:8208",
    "movistar_id": "ANTV",
    "movistar_nombre": "Canal Sur Andalucía",
    "movistar_numero": "150",
    "tvh_id": "ANTV.es",
    "tvh_m3u": false,
    "tvh_nombre": "Canal Sur Andalucía",
    "tvh_tag": "SD|TV"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.3.37:8208",
    "movistar_id": "TVG",
    "movistar_nombre": "TV Galicia",
    "movistar_numero": "151",
    "tvh_id": "TVG.es",
    "tvh_m3u": false,
    "tvh_nombre": "TV Galicia",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.3.36:8208",
    "movistar_id": "TVC",
    "movistar_nombre": "TV3 Cat",
    "movistar_numero": "153",
    "tvh_id": "TVC.es",
    "tvh_m3u": false,
    "tvh_nombre": "TV3 Cat",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.60:8208",
    "movistar_id": "ETB",
    "movistar_nombre": "ETB Sat",
    "movistar_numero": "154",
    "tvh_id": "ETB.es",
    "tvh_m3u": false,
    "tvh_nombre": "ETB Sat",
    "tvh_tag": "SD|REMOTE"
  },
  {
    "movistar_epg": false,
    "movistar_fuente": "239.0.0.81:8208",
    "movistar_id": "ARAGON",
    "movistar_nombre": "Aragón TV Int",
    "movistar_numero": "155",
    "tvh_id": "ARAGON.es",
    "tvh_m3u": false,
    "tvh_nombre": "Aragón TV Int",
    "tvh_tag": "SD|TV"
  }
];

export default cadenasREMOTE;

